### ISSUE TITLE
scan problem

### ISSUE THREAD

**Issue by chenxiyu199506** [dark-lbp/snmp_fuzzer#1]
i meet a trouble;
[ERROR] [snmp_set_fuzz.oid_scan] -> Layer [SNMP] not found
why that?

**Comment by dark-lbp** [comment]
Can you provide more detial like python version, os version, scapy version and snmp scan pcap file?

**Comment by chenxiyu199506** [comment]
python 2.7.15+ OS Ubuntu 15.04 scapy 2.4.3rc2   
because of dont execute to save ,so not pcap , but have log.
[20190703-172909.log](https://github.com/dark-lbp/snmp_fuzzer/files/3354396/20190703-172909.log)

**Comment by chenxiyu199506** [comment]
![image](https://user-images.githubusercontent.com/48797813/60582820-1b5cf480-9dbc-11e9-8363-cdac50aabce2.png)

**Comment by chenxiyu199506** [comment]
scan config 
target = '192.168.0.102'
port = 80
count = 10
nic = conf.route.route(target)[0]
Target = SnmpTarget(name='test102', monitor_port=port, community='public', oid='.1.3', version=2, target=target,  nic=nic, fuzz_count=count)
Target.oid_scan()
Target.save_scan_result()

snmp in VM win server 2008

**Comment by dark-lbp** [comment]
hmm, you can use wireshark or tcpdump to save packet to pcap.

**Comment by chenxiyu199506** [comment]
[test.zip](https://github.com/dark-lbp/snmp_fuzzer/files/3357255/test.zip)
this is pcap ,soming went wrong when oid was 1.3.6.1.2.1.4.31.1.1.3.2  1.3.6.1.2.1.4.31.1.1.4.1

anyhow ,thank you！

**Comment by dark-lbp** [comment]
looks like Scapy can't recognize the snmp response packet(packet No.1404 in test.pcap file).
This might takes sometime to analyze.
```python
rsp_packet = rdpcap('test.pcap')

# Get-next-request(packet No.1403 in test.pcap)
In [5]: pkts[1402].show()
###[ Ethernet ]###
  dst       = b8:27:eb:b8:4b:87
  src       = d8:f2:ca:07:7d:e4
  type      = IPv4
###[ IP ]###
     version   = 4
     ihl       = 5
     tos       = 0x0
     len       = 71
     id        = 1
     flags     =
     frag      = 0
     ttl       = 64
     proto     = udp
     chksum    = 0xf886
     src       = 192.168.0.104
     dst       = 192.168.0.102
     \options   \
###[ UDP ]###
        sport     = snmp
        dport     = snmp
        len       = 51
        chksum    = 0x27d6
###[ SNMP ]###
           version   = 'v2c' 0x1 <ASN1_INTEGER[1]>
           community = <ASN1_STRING['public']>
           \PDU       \
            |###[ SNMPnext ]###
            |  id        = 0x0 <ASN1_INTEGER[0]>
            |  error     = 'no_error' 0x0 <ASN1_INTEGER[0]>
            |  error_index= 0x0 <ASN1_INTEGER[0]>
            |  \varbindlist\
            |   |###[ SNMPvarbind ]###
            |   |  oid       = <ASN1_OID['.1.3.6.1.2.1.4.31.1.1.3.2']>
            |   |  value     = <ASN1_NULL[0]>

# Get-next-response(packet No.1404 in test.pcap)
In [6]: pkts[1403].show()
###[ Ethernet ]###
  dst       = d8:f2:ca:07:7d:e4
  src       = b8:27:eb:b8:4b:87
  type      = IPv4
###[ IP ]###
     version   = 4
     ihl       = 5
     tos       = 0x0
     len       = 74
     id        = 20251
     flags     = DF
     frag      = 0
     ttl       = 64
     proto     = udp
     chksum    = 0x6969
     src       = 192.168.0.102
     dst       = 192.168.0.104
     \options   \
###[ UDP ]###
        sport     = snmp
        dport     = snmp
        len       = 54
        chksum    = 0x5ec9
###[ Raw ]###
           load      = '0,\x02\x01\x01\x04\x06public\xa2\x1f\x02\x01\x00\x02\x01\x00\x02\x01\x000\x140\x12\x06\x0b+\x06\x01\x02\x01\x04\x1f\x01\x01\x04\x01F\x03\x00\xc3\xba'


```

**Comment by chenxiyu199506** [comment]
thank u，dube， i  try modify the test_scan_oid.py oid_scan (line 163) except, temprary use 'break' replace 'pass'.

**Comment by dark-lbp** [comment]
Thanks, fixed with https://github.com/dark-lbp/snmp_fuzzer/commit/7c65412178859285efc99355cb1f0941ddd48521
